README-ch.md
README.md
chap-header.php

It's better to call "Chinese translation" "中文版" than "中国的翻译".

change the translation of 'Chinese translation'

---

11/README.md

Perlin's "Improved Noise" with quintic interpolation is separate from Simplex Noise, which does not even use interpolation. The contributions from each simplex corner are added, not blended. I created a separate section "Improved Noise" to hold the explanation of the quintic interpolation polynomial (which is not a Hermite polynomial, btw).

Quintic interpolation moved to separate section

---

01/README.md

I made a small change to the last sentence of line 18:
```
Original:  "Each pipe is also known as *thread*."
Corrected: "Each pipe is also known as a *thread*."
^
```
It's also saying I made a change on line 48, but I didn't. The text there is the same as it was before.
¯\\\_(ツ)\_/¯

Fixed a small typo

---

appendix/00/README-de.md
appendix/00/README-it.md
appendix/00/README.md

Fixes #128 
[This SO thread](http://stackoverflow.com/questions/14927157/git-dependency-hell-submodule-pull-failing) provides a bit more context, but rather than running `git pull` within each submodule, I believe we should be running `git submodule init && git submodule update`. 
Doing so, in my case, resolved the error described in #128 and retrieved each submodule's content as expected.

Fix readme command for offline installing

---

makefile
src/makeThumbs.py
src/parseBook.py

Because on distributions like ArchLinux `/usr/bin/python` is a link to `python3`, so the script fails without virtualenv ...

Update Makefile with explicit Python version

---

03/README-ch.md
03/README-de.md
03/README-es.md
03/README-fr.md
03/README-it.md
03/README-jp.md
03/README-kr.md
03/README.md

As far as I can see shadertoy no longer has iGlobalTime uniform, it was replaced with iTime. Under the following link you can find current input uniforms: [https://www.shadertoy.com/howto](https://www.shadertoy.com/howto)

replace iGlobalTime with iTime

---

README-ru.md
README.md
chap-header.php
toc-header.php

I removed extra link to Russian translation, which was already there since commit 7d9549c04b373ec1ec729198c8252bd0dcb18043. Also added Facebook page to acknowledgements. Thanks for updating the website!

Fix headers and acknowledgements.

---

css/style.css

Text was wrapping oddly on the Hello World because the code and canvas block did not have a minimum height. This could be refactored further in favor of CSS Grids.

+ min-height on .codeAndCanvas

---

11/README-jp.md

Hello, 
This is a small patch for the Japanese translation in chapter 11.
I changed some mathematical expressions in Japanese.
> ... with a quintic interpolation curve ( _f(x) = 6x^5-15x^4+10x^3_ )
The "4次エルミート曲線" is not a correct translation of "quintic interpolation curve".
I think that "5次式の曲線" would be better.
Thanks.

A patch for the Japanese translation

---

11/2d-gnoise.frag
11/circleWave-noise.frag
11/splatter.frag
11/tmp/warp-grid.frag

in four shaders a function that implements gradient noise was labeled as
value noise and linked to IQ's value noise example on shadertoy. this pr
labels that function as gradient noise and instead links to IQ's gradient noise
example on shadertoy.
this tripped me up as someone who was trying to learn the difference between the two

correct references to gradient noise

---

appendix/01/README-de.md

Since the `line-height` is set to 0px, this headline is breaking into two lines and overlaps with itself. Easiest fix is to just shorten the headline.

Fix breaking headline

---

toc-header.php

It removes an invalid character from the toc-header.
Before:
After:
Thanks.

Removed an invalid character on the header

---

05/linear.frag

except if there is a pedagogical reason for using smoothstep twice, using it once seems simpler to understand

simplify smoothstep maths

---

css/style.css

Reason: described functionality is used in line 2, not 1.

CSS: Remove an empty rule

---

05/README-ch.md
05/README-de.md
05/README-es.md
05/README-fr.md
05/README-it.md
05/README-jp.md
05/README-kr.md
05/README-pt.md
05/README-ru.md
05/README-vi.md
05/README.md

Golan recently updated his site, and a few of his links to shaping functions now live at flong.com/archive, so I made the quick fix :)

Updating broken flong.com links

---

header.php

was getting the following error from a clean build using php 8.1.2:
```
"Warning: Undefined array key "lan" in ~/thebookofshaders/header.php on line 4"
```
Was going to use `isset` but it seems like a banged `!empty` is used elsewhere. am not a php dev so will defer to anyone who feels more confident.

fix `undefined array key "lan"` error

---

appendix/02/README.md

From brew:
> Error: `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.

Update brew install cask command

---

11/README.md

we're interpolating between `floor`ed points to which `rand` is additionally applied - not `fract`. 
See also code excerpt:
```
// Four corners in 2D of a tile
float a = random(i);
float b = random(i + vec2(1.0, 0.0));
float c = random(i + vec2(0.0, 1.0));
float d = random(i + vec2(1.0, 1.0));
```

fix: mentioned 'fract' instead of 'rand'

---

03/README-es.md

There were code block backticks around the second example html tags preventing the example to render properly. Now the backticks are gone and the example does render on screen.

Fix render of second example in README-es.md

---

.github/workflows/publish.yml

HI @patriciogonzalezvivo,
Thanks for your great work. In order for your users to get EPUB / PDF and TEX versions of your book without the need to clone the repo, I created a github action that do it for them. 
When you'll push a tag version (e.g. `v1.0.0`, for example), the three book formats will be built and pushed to release. You can see the consequence on my forked repo.
The release artifacts are there https://github.com/sroucheray/thebookofshaders/releases
The action that built it is here https://github.com/sroucheray/thebookofshaders/actions/runs/2840310688
Hope you'll find it useful.
Cheers,
Stephane

Create a github action to build and release the book

---

appendix/02/README-id.md
appendix/02/README-vi.md
appendix/02/README.md

Today I tried to get pdf version of The book of shaders. And was following the steps mention on readme.md file. I got stuck at one place. [Apparently brew no longer support `brew cask`](https://github.com/Homebrew/discussions/discussions/340#discussioncomment-232364). I have updated to the latest command that worked for me.

Updated print guide instruction for homebrew cask

---

README-pl.md
README.md
chap-header.php
toc-header.php

As in the title:
- I've added acknowledgment for Polish translation, 
- updated the header so the link to switch to Polish version is present
- in ToC, when clicking the article links, the user is redirected to polish version instead of the default english one

Polish translation - fixes (acknowledgment, header, linking to polish articles)

---

footer.php

This small fix sets the theme earlier, which prevents flicker when it changes from light to dark too abruptly

Theme: Prevent flicker on first load

---

00/README-ch.md
README-ch.md

- Fixed links to appendix entries
- Fixed a translation in `00/README-ch.md` (previous Chinese translation means "on a Raspberry Pi **instead of** a browser" instead of "on a Raspberry Pi **without** a browser")

Fix issues in Chinese translation

---

07/shapes.frag

Labeling 'r' as radius is misleading when it is actually the number of radians representing some segment of the circle for a triangle edge.
Feel free to adjust/rewrite the new comments!
Generally, I think this could afford to have even more comments / more aptly named variables, but this is at least removing an incorrect statement.
Thanks!

Fix misleading comment in shapes example.
