patriciogonzalezvivo/thebookofshaders

- 00/README.md
Correcting the name of the company that created Journey.
> The Game Company -> That Game Company

- README-ch.md
Starting to translate the book into Chinese!
> add readme-ch

- 03/README-ch.md
- 04/README-ch.md
It's about 12pm of the last day of 2015 here in China, so... happy new year! XD
> add chapter 03,04 of translation-ch

- 09/README-ch.md
1st round translation of ch09 pattern
> chapter 9 pattern

- 00/README-kr.md
- README-kr.md
Hi,
Here is Main README-kr.md and chapter 00's README-kr.md.
01 should be do pull request end of this week or on monday next week!
Let me know if there is any issues. This will be my first pull request to thebookofshaders repo.
Thanks,
Jae
> first pull request for korean translation

- 10/README-ch.md
chapter 10 Chinese translation initial commit
> chapter 10 Chinese translation

- README-kr.md
It is in line 88
"한국어 번역을 맡고 있는 [Jae Hyun Yoo](https://www.facebook.com/fkkcloud) 에게 감사를 표합니다. [Korean translation (한국어)](?lan=kr)"
Let me know if there is anything else that I have to add.
Thanks!
> adding credit line for Korean translator

- 00/README-fr.md
- README-fr.md
Hello
Here is the beginning of the french translation of your book.
Thanks for your great work.
> cover page and introduction chapter translated

- 03/README-kr.md
- 04/README-kr.md
Chapter 3 and 4 Korean Translation Merge
> chapter 3 and 4 korean translation

- .gitignore
- 00/README-fr.md
- 01/README-fr.md
- 01/notes.md
- 02/README-fr.md
here are the first 3 chapters in french and a note in 01/notes.md 
I think it would be better to have all the translations ready before adding the "french" to the language bar :)
you can safely ignore the modifications done on .gitignore and the parsedown/ file, that's just me being a noob with GIT...
> bonjour world!

- 03/README-fr.md
- 03/README.md
- 03/notes.md
> FR : chapter 3, notes (+ 1 typo in EN version)

- 04/README-ch.md
- 04/README-es.md
- 04/README-fr.md
- 04/README-jp.md
- 04/README-kr.md
- 04/README.md
found a broken link, just changed the URL to this one http://openframeworks.cc/ofBook/chapters/shaders.html
> fix link to openframeworks shader tutorial.

- 12/README.md
As requested, I edited the text for release. I think it's ready for publication now.
> Chapter 12 edited

- appendix/03/README.md
I assume this is the intended English word?
> Fix "embebed" -> "embedded".

- 04/README.md
I think the concept you're expressing is "live examples"? An alternate way of expressing this that might also be clearer is "interactive examples".
> Use phrase "live examples" rather than "life examples"

- 13/README.md
Fleshed out some sections, added a few short paragraphs, and did a general language and spelling check.
> Edited for release

- css/style.css
- index.php
- toc-header.php
Added language links to the top page
I met a couple of students who are big fan of the book of shaders. They told me they didn't notice there are other languages for a while since the top page doesn't have links...
> Add language links to the top page

- README-jp.md
fix broken link to moon.frag
add links to chapter 12 and 13
> Translation jp

- 12/README.md
It's "that allows" not "thatallows".
> Fixed a typo.

- 13/README.md
> some small typo corrections chapter 13

- README-fr.md
updated the french index with links to the chapters 12 & 13
> index FR update

- appendix/02/README.md
> Update Appendix 2 with python2.7 install instructions

- appendix/02/README.md
Okay, I promise that this is my last too small PR about Python's missing dependency!
> Update README.md of Appendix 2

- .editorconfig
> Create an EditorConfig file

- appendix/00/index.php
- appendix/01/index.php
- appendix/02/index.php
- appendix/03/index.php
- appendix/04/index.php
- appendix/05/index.php
- appendix/06/index.php
- appendix/index.php
Multilingual URLs do not work on thebookofshaders.com/appendix/
> Fix issue #152

- .travis.yml
- src/makeThumbs.py
- src/parseBook.py
I worked a bit on this last night and now I am facing a dilemma and I would like your opinion @patriciogonzalezvivo:
This configuration is quite simple, I just have to build `glfw` and `glfwViewer` by hand because these two programs are not available in the standard Ubuntu Trusty repositories, which is the distribution used by default by Travis CI.
And I have to add `texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended` to the dependencies to avoid the following two problems:
```
Successful building of ./book.tex
pandoc: Error producing PDF from TeX source.
! Font T1/cmr/m/n/10=ecrm1000 at 10.0pt not loadable: Metric (TFM) file or inst
alled font not found.
<to be read again> 
relax 
l.100 \fontencoding\encodingdefault\selectfont
Error in building of ./book.pdf
```
``` …
```
> Create a TravisCI configuration to check PDF building of the book

- src/makeThumbs.py
- src/parseBook.py
https://github.com/hhatto/autopep8
> Make the Python scripts follow the PEP8 code style

- 05/README-jp.md
Hello, I found some mistakes in Japanese translation.
Thanks.
> Corrects some mistakes in the Japanese version of Chapter 05

- 13/2d-fbm.frag
- 13/README-ch.md
- 13/README.md
- 13/turbulence.frag
Replace amplitud with amplitude.
> typo fixes

- README-ru.md
- examples/README-ru.md
It seems that all chapters are translated :)
Should we also translate glossary content and modify corresponding php code for correct language-dependent redirections?
> Translate examples gallery abstract into Russian.

- docker-compose.yml
With this, if you have docker and docker-compose installed, starting up the book is a simple matter of `docker-compose up` and then you'll find the book up at `http:\\localhost:8000` simple as that
> Add docker-compose file for easy setup

- 07/README.md
`as is describe ...` -> `as is described ...`
> Fix typo in the 07 chapter

- 05/README-es.md
There's one thing I didn't change but I'd like to ask any reviewer to consider it. This expression was confusing Spanish speaker for Spain: 'Ten en cuenta que estas funciones son nuestra cerca', since we don't use 'cerca' as fence, but only as close (not far). I realised that it's also used at the beginning of the chapter, but that time I read 'cera' (wax), which is probably a good translation since it carries the same message, being the most basic set of tools that can be used.
> Fix some typos

- README-pt.md
So far I only translated the README but it's a start!
> Add README translation in Portuguese

- 00/README-pt.md
- 01/README-pt.md
I had to fix a typo in the previous page too :/
> Translation pt 01

- 01/README-fr.md
- 03/README-fr.md
- 08/README-fr.md
- 11/README-fr.md
- 13/README-fr.md
No ellipsis after [etc](https://www.projet-voltaire.fr/regles-orthographe/etc-ou-etc/).
> Remove ellipsis after etc

- 04/README.md
Thanks for this awesome resource!
> Fix typo in 04

- 12/README.md
> Fixed typo in README.md

- 05/README.md
`PI` isn't a function, it's a constant definition.
> "call to PI" -> "use of PI"

- 09/grid-making.frag
Just a small fix with spelling mistake in code sample.
> Fix spelling mistake with 09 

- 13/README-pt.md
Hello, Patricio, this is the translation of the chapter 13
> Chapter 13's portuguese translation.

- 11/2d-vnoise.frag
Clicking value noise image in chapter 11 gives error currently. This adds the missing file using the noise function from https://www.shadertoy.com/view/lsf3WH
> Added the missing 2d-vnoise.frag in chapter 11

- src/makeThumbs.py
- src/parseBook.py
I'm attempting to make use of Python 3 syntax with as much compatibility as possible with Python 3.4.
I incidentally use this fork of the directory on my Android phone for browing the book.
> Trivially upgrade to Python 3

- src/parseBook.py
The src/parseBook.py script wasn't working for me because of a missing ')'
> Missing parentheses

- 00/README-id.md
- 01/README-id.md
- 02/README-id.md
- 03/README-id.md
- 04/README-id.md
- 05/README-id.md
- 06/README-id.md
- 07/README-id.md
- 08/README-id.md
- 09/README-id.md
- 10/README-id.md
- 11/README-id.md
- 12/README-id.md
- 13/README-id.md
- README-id.md
- appendix/00/README-id.md
- appendix/01/README-id.md
- appendix/02/README-id.md
- appendix/03/README-id.md
- appendix/README-id.md
- chap-header.php
- examples/README-id.md
- examples/README.md
- toc-header.php
Hi, I added bahasa Indonesia translation to The Book of Shaders
> Added Bahasa Indonesia Translation

- 04/README-de.md
- 04/README-fa.md
- 04/README-fr.md
- 04/README-id.md
- 04/README-it.md
- 04/README-jp.md
- 04/README-pt.md
- 04/README-ru.md
- 04/README-vi.md
- 04/README.md
- 04/sfml/CMakeLists.txt
- 04/sfml/data/shader.frag
- 04/sfml/src/main.cpp
I totally understand if you want to keep it limited to the three mentioned frameworks (+ blender), I just thought as I went through the book and had already created such an example using SFML, it would be a shame if I didn't try and share it with others.
If you want, I could also write a paragraph for it (in English and German).
> Add SFML to the framework list

- src/parseBook.py
> Update glslviewer command used for pdf & epub

- 05/README-es.md
Since this is the spanish file I guess I can write in spanish, but lmk if you need a english explanation!
La linea 19 posee la definicion de la funcion `main` y no la linea que define `y` con el exponente.
Este "typo" tiene sentido porque en la primera version si era la linea 19, pero con cambios este numero de linea cambio hasta el 22.
> [ES] Referencia a linea debe ser actualizada

- 04/README.md
Not sure if you're taking PRs, but I believe there might be a typo here :)
> Fix typo in chapter 4

- 04/README-ch.md
translated changed content in [commit 6441e53](https://github.com/patriciogonzalezvivo/thebookofshaders/commit/6441e53bcf83de8758a3a11dca37426194217b12).
> translate appending content in README-ch.md in ch04

- css/style.css
- src/main.js
This button is styled as normal link in the header. Applying a filter to invert colors except on the images, `canvas` and `iframe` elements.
> Add dark theme toggle button

- 09/README.md
deleting a TODO line which definitely shouldn't be displayed to the users. At the same time applying changes which this TODO proposed
> Deleting and applying a probably unintended TODO

- docker-compose.yml
I was getting this error when running `docker-compose up`:
(root) Additional property web is not allowed
The changes in `docker-compose.yml` fixed it for me.
> Fix docker compose error

- Makefile
Updated Makefile commands (python@2.7 -> python@3). This remedied issue with creating a .pdf of the book.
> Makefile python3

- 07/README-fr.md
I found a few typos in the French version and wanted to correct them
> fix a few typos in french version

- 05/README.md
I added a missing space :)
EDIT: _only for the english version_
> Fix (typo): 05/Algorithmic Drawing - Missing space between words

- chap-header.php
- languages.php
- toc-header.php
Fixes a problem where it is impossible to select the Ukrainian language on some pages.
> Fix languages menu bug
